# Site settings
title: eHappy
email: clarkwyca@gmail.com
description: "eHappy"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ehappy.ca" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  clarkwyca

# Build settings
markdown: kramdown
